name: Smart App - Regression Tests
on:
  # Trigger workflow on any push o rpull to any branch, example master
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    cron: "0 10 */14 * 4"

  # what will be triggered?
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env:
      APP_BASE_URL: ${{ vars.APP_BASE_URL }}
      USERNAME: ${{ vars.USERNAME }}
      PASSWORD: ${{ vars.PASSWORD }}

    # what ubuntu do?
    steps:
      # clone and initialize repository
      - name: Checkout
        uses: actions/checkout@v4

      # install my dependencies
      - name: Install Dependencies and Run Regression Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headed: false
          command: npm run test:regression

      #Generate a report
      - name: Publish Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Cypress HTML Reports
          path: cypress/reports/
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
